[[Exodus]]
arch = "aarch64"
git-tree-sha1 = "454aa1056b498ff9c8227d363ddf3f1173fdc983"
os = "macos"

    [[Exodus.download]]
    sha256 = "109c2d55b0210db54ae931c09bffdbb64e31fd6324dc41360656d80b494af84d"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.aarch64-apple-darwin.tar.gz"
[[Exodus]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4073b24c2a4042dbea7dffebcafdf1846c51118"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "9f83122cc327604c82442701dd5459c456c2f765f25f31672f3d166935131700"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Exodus]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dce8d0b16308bd9c6dcd7cf93df8a56e8e9bbdf"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "70a92f5c4ff5bccffaf5008d032bfc1fe7bc101518ec7a377bd76d168c34291d"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Exodus]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "196087d42c64bfff703bf1a9972caa97597f981e"
os = "windows"

    [[Exodus.download]]
    sha256 = "79880c6ddf4924cf9cc52a1d9c57a0680d83b6f7bb0e979fd42041812cd0fad3"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.i686-w64-mingw32-cxx03.tar.gz"
[[Exodus]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31278b80af8a40d6888e5d20381e0fc094fe4320"
os = "windows"

    [[Exodus.download]]
    sha256 = "1903688d283c4aba9b113673bc1d37ea425f16d637df9a847bddbf0137c3afeb"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.i686-w64-mingw32-cxx11.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "21cf8e25ed9bfa1031d9f4eed57a2ab7b4ff1493"
os = "macos"

    [[Exodus.download]]
    sha256 = "7f9410c9eb96ccd797c63c771731fe46dcbe3228426e76936c24a996f802bc3c"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.x86_64-apple-darwin.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d09ca3a9fd598a9f0a575257113d6a5553f9dff0"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "ed591a12797fd9ff57350553e06ae9e84f252f0de5d90c69dcaf43df261a5a22"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc5df6750d5ee879a8e8c27d2f5de9a134d282bb"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "01a7be02a15427bd35886a61e58dead6d5532b85fe5ca1f8a07d303cec1a65d5"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "420676ff3c7ad9c83816ca8bbe6b0197ead343e6"
os = "windows"

    [[Exodus.download]]
    sha256 = "c7aad464557f784503d07f4ed687782b503bb95d993a19a40fd73bd7c477bfce"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "266b0d55d4e817051f874ac12519d224b2a5ef84"
os = "windows"

    [[Exodus.download]]
    sha256 = "c3a4c7d139ac462bd3c6d42832ce28ec9217cd376151825a4f72bbdc12239e8b"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v8.19.0+0/Exodus.v8.19.0.x86_64-w64-mingw32-cxx11.tar.gz"
