[[Exodus]]
arch = "aarch64"
git-tree-sha1 = "640d1aac9fd96b4d7583875e40af1c8acfb86a10"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "69e6aea4552c5f2993a5db0221aa7c09700a6d7c3043de1f096d4d4d4b0c3af8"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v0.1.1+0/Exodus.v0.1.1.aarch64-linux-gnu.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "9dda2f7ba6318fb5712faed8cfb84f60ce75ea24"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "b523aba12d467ef73b897c08761d3f06c2ebe5979541321ae0813af8c790acfa"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v0.1.1+0/Exodus.v0.1.1.x86_64-linux-gnu.tar.gz"
