[[Exodus]]
arch = "aarch64"
git-tree-sha1 = "cb97bff625b05f6421834d92f04cdef30bb096dc"
os = "macos"

    [[Exodus.download]]
    sha256 = "2c7cc3bfa720b7a11ea6924af30c2d08641ed5688d803239b9685132fb2d01b9"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.aarch64-apple-darwin.tar.gz"
[[Exodus]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc338ade7402d1f6bbfe2c53a25cb1e2c4d2bb74"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "6467eaf1d666e1e8cd2366c2592c1b64492121f5876d94362d3b5609f713be85"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Exodus]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37000f3df7ea308867752f6789ac8f9b2528dc5a"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "90360e61ebfd62145111ebef5f800e77698c30f83bdbcae3ecbbd31e83d98fb4"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Exodus]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1dd769669aa4df4a1a0c73a409a744d03faf01a"
os = "windows"

    [[Exodus.download]]
    sha256 = "cbf6ed64d2f425d103113e180550a32ad577c8de8245185972d9e1c36a269463"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[Exodus]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fc187dc1ac62d077c8f71b56792304040a284b0"
os = "windows"

    [[Exodus.download]]
    sha256 = "8c1d99fac0350ced851a67b6c608524331fddf1d33e1d8a202702343d3cbaca2"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "98390bc77c3ad693b9f9441665bbad4f6afa46c0"
os = "macos"

    [[Exodus.download]]
    sha256 = "ed01993288761678b674824e45b54d5a1b15c929fb6cd7c64779b5eeb00137ca"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.x86_64-apple-darwin.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43bfeccb6f436ae5182bffdc0b17c0c8578c5944"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "a5ba24edb924ec94081f97d2043771aa9b68eac5873593b8fdee0ff4275bf99d"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff40fb9ed2e60f0b60b567c54f939ad225318e0b"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "5013bccf3bf1a59c416a097aee18995f3b5af8106a677df7301bea797383f749"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "187adf4ca1593c4c36aa92f5655d09869be31249"
os = "windows"

    [[Exodus.download]]
    sha256 = "7b567a64c006f1419ed7c6cfac11fa49546ce749ae6949ee0e78849c63937cc2"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31bdc57e3f2eda57101abebcfb5e9a5d29c95e78"
os = "windows"

    [[Exodus.download]]
    sha256 = "4a2cfb62fa0116b4c97bb12f544927faae9f2aef5f7f24166516d78bfd26d16e"
    url = "https://github.com/JuliaBinaryWrappers/Exodus_jll.jl/releases/download/Exodus-v9.4.0+0/Exodus.v9.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
